name: "Lint"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - stable-*.*
  schedule:
    # Every day at 3:30 AM UTC
    - cron: '30 3 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: "Check out the repository"
      uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
    - name: "Install gaplint with pip"
      run: pip install gaplint
    - name: "Run gaplint on the graphviz package"
      run: |
      gaplint gap/*.g* tst/*.tst examples/*.g* PackageInfo.g init.g read.g makedoc.g tst/testall.g
